import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux'
import { store } from "@/lib/store";
import StateWrapper from "@/components/state-wrapper/state-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fledge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F2F2F2]">
        <StateWrapper>
          {children}
        </StateWrapper>
      </body>
    </html>
  );
}
